// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.2
// source: app.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"` // 空字符串表示未安装
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Icon          string                 `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppEntry) Reset() {
	*x = AppEntry{}
	mi := &file_app_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppEntry) ProtoMessage() {}

func (x *AppEntry) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppEntry.ProtoReflect.Descriptor instead.
func (*AppEntry) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{0}
}

func (x *AppEntry) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *AppEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppEntry) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AppEntry) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *AppEntry) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

type AppCheckReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 要检测的应用 ID 列表，空表示检测所有
	AppIds        []string `protobuf:"bytes,1,rep,name=app_ids,json=appIds,proto3" json:"app_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppCheckReq) Reset() {
	*x = AppCheckReq{}
	mi := &file_app_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppCheckReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppCheckReq) ProtoMessage() {}

func (x *AppCheckReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppCheckReq.ProtoReflect.Descriptor instead.
func (*AppCheckReq) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{1}
}

func (x *AppCheckReq) GetAppIds() []string {
	if x != nil {
		return x.AppIds
	}
	return nil
}

type AppCheckResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*AppEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppCheckResp) Reset() {
	*x = AppCheckResp{}
	mi := &file_app_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppCheckResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppCheckResp) ProtoMessage() {}

func (x *AppCheckResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppCheckResp.ProtoReflect.Descriptor instead.
func (*AppCheckResp) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{2}
}

func (x *AppCheckResp) GetEntries() []*AppEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type AppInstallReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppInstallReq) Reset() {
	*x = AppInstallReq{}
	mi := &file_app_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppInstallReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppInstallReq) ProtoMessage() {}

func (x *AppInstallReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppInstallReq.ProtoReflect.Descriptor instead.
func (*AppInstallReq) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{3}
}

func (x *AppInstallReq) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

var File_app_proto protoreflect.FileDescriptor

const file_app_proto_rawDesc = "" +
	"\n" +
	"\tapp.proto\x12\tnexus.pkg\"\x7f\n" +
	"\bAppEntry\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x12\n" +
	"\x04icon\x18\x05 \x01(\tR\x04icon\"&\n" +
	"\vAppCheckReq\x12\x17\n" +
	"\aapp_ids\x18\x01 \x03(\tR\x06appIds\"=\n" +
	"\fAppCheckResp\x12-\n" +
	"\aentries\x18\x01 \x03(\v2\x13.nexus.pkg.AppEntryR\aentries\"&\n" +
	"\rAppInstallReq\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appIdB)Z'github.com/Tudyha/nexus/pkg/proto/protob\x06proto3"

var (
	file_app_proto_rawDescOnce sync.Once
	file_app_proto_rawDescData []byte
)

func file_app_proto_rawDescGZIP() []byte {
	file_app_proto_rawDescOnce.Do(func() {
		file_app_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_proto_rawDesc), len(file_app_proto_rawDesc)))
	})
	return file_app_proto_rawDescData
}

var file_app_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_app_proto_goTypes = []any{
	(*AppEntry)(nil),      // 0: nexus.pkg.AppEntry
	(*AppCheckReq)(nil),   // 1: nexus.pkg.AppCheckReq
	(*AppCheckResp)(nil),  // 2: nexus.pkg.AppCheckResp
	(*AppInstallReq)(nil), // 3: nexus.pkg.AppInstallReq
}
var file_app_proto_depIdxs = []int32{
	0, // 0: nexus.pkg.AppCheckResp.entries:type_name -> nexus.pkg.AppEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_app_proto_init() }
func file_app_proto_init() {
	if File_app_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_proto_rawDesc), len(file_app_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_proto_goTypes,
		DependencyIndexes: file_app_proto_depIdxs,
		MessageInfos:      file_app_proto_msgTypes,
	}.Build()
	File_app_proto = out.File
	file_app_proto_goTypes = nil
	file_app_proto_depIdxs = nil
}
