// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.2
// source: common.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息类型
type MessageType int32

const (
	MessageType_ENVELOPE_TYPE_UNKNOWN MessageType = 0
	// 1-30 系统级消息
	MessageType_HANDSHAKE     MessageType = 1  // 握手请求
	MessageType_HANDSHAKE_ACK MessageType = 2  // 握手响应
	MessageType_HEARTBEAT     MessageType = 3  // 心跳请求
	MessageType_HEARTBEAT_ACK MessageType = 4  // 心跳响应
	MessageType_DISCONNECT    MessageType = 5  // 断开连接
	MessageType_EXIT          MessageType = 30 // 客户端退出程序
	// 31-40 tunnel消息
	MessageType_TUNNEL_OPEN     MessageType = 31 // 创建 tunnel
	MessageType_TUNNEL_OPEN_ACK MessageType = 32 // 创建 tunnel 响应
	// 41-50 任务消息
	MessageType_TASK          MessageType = 41 // 下发任务
	MessageType_TASK_PROGRESS MessageType = 42 // 任务进度上报
	// 51-60 进程管理
	MessageType_PROCESS_LIST MessageType = 51 // 列出进程
	MessageType_PROCESS_KILL MessageType = 52 // 终止进程
	// 61-70 文件管理
	MessageType_FILE_LIST     MessageType = 61 // 列出目录
	MessageType_FILE_DOWNLOAD MessageType = 62 // 下载文件
	MessageType_FILE_UPLOAD   MessageType = 63 // 上传文件
	MessageType_FILE_DELETE   MessageType = 64 // 删除文件/目录
	MessageType_FILE_MKDIR    MessageType = 65 // 创建目录
	MessageType_FILE_RENAME   MessageType = 66 // 重命名文件/目录
	// 71-80 网络管理
	MessageType_NETWORK_LIST MessageType = 71 // 列出网络连接
	// 81-90 应用管理
	MessageType_APP_CHECK   MessageType = 81 // 检测已安装应用
	MessageType_APP_INSTALL MessageType = 82 // 安装应用
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:  "ENVELOPE_TYPE_UNKNOWN",
		1:  "HANDSHAKE",
		2:  "HANDSHAKE_ACK",
		3:  "HEARTBEAT",
		4:  "HEARTBEAT_ACK",
		5:  "DISCONNECT",
		30: "EXIT",
		31: "TUNNEL_OPEN",
		32: "TUNNEL_OPEN_ACK",
		41: "TASK",
		42: "TASK_PROGRESS",
		51: "PROCESS_LIST",
		52: "PROCESS_KILL",
		61: "FILE_LIST",
		62: "FILE_DOWNLOAD",
		63: "FILE_UPLOAD",
		64: "FILE_DELETE",
		65: "FILE_MKDIR",
		66: "FILE_RENAME",
		71: "NETWORK_LIST",
		81: "APP_CHECK",
		82: "APP_INSTALL",
	}
	MessageType_value = map[string]int32{
		"ENVELOPE_TYPE_UNKNOWN": 0,
		"HANDSHAKE":             1,
		"HANDSHAKE_ACK":         2,
		"HEARTBEAT":             3,
		"HEARTBEAT_ACK":         4,
		"DISCONNECT":            5,
		"EXIT":                  30,
		"TUNNEL_OPEN":           31,
		"TUNNEL_OPEN_ACK":       32,
		"TASK":                  41,
		"TASK_PROGRESS":         42,
		"PROCESS_LIST":          51,
		"PROCESS_KILL":          52,
		"FILE_LIST":             61,
		"FILE_DOWNLOAD":         62,
		"FILE_UPLOAD":           63,
		"FILE_DELETE":           64,
		"FILE_MKDIR":            65,
		"FILE_RENAME":           66,
		"NETWORK_LIST":          71,
		"APP_CHECK":             81,
		"APP_INSTALL":           82,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

// 错误码
type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNKNOWN ErrorCode = 0
	ErrorCode_SUCCESS            ErrorCode = 1 // 成功
	ErrorCode_FAILED             ErrorCode = 2 // 失败
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_UNKNOWN",
		1: "SUCCESS",
		2: "FAILED",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNKNOWN": 0,
		"SUCCESS":            1,
		"FAILED":             2,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

// 隧道类型
type TunnelType int32

const (
	TunnelType_TUNNEL_TYPE_UNKNOWN TunnelType = 0
	TunnelType_TCP                 TunnelType = 1 // TCP 隧道
	TunnelType_UDP                 TunnelType = 2 // UDP 隧道
	TunnelType_PTY                 TunnelType = 3 // 伪终端隧道
)

// Enum value maps for TunnelType.
var (
	TunnelType_name = map[int32]string{
		0: "TUNNEL_TYPE_UNKNOWN",
		1: "TCP",
		2: "UDP",
		3: "PTY",
	}
	TunnelType_value = map[string]int32{
		"TUNNEL_TYPE_UNKNOWN": 0,
		"TCP":                 1,
		"UDP":                 2,
		"PTY":                 3,
	}
)

func (x TunnelType) Enum() *TunnelType {
	p := new(TunnelType)
	*p = x
	return p
}

func (x TunnelType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TunnelType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[2].Descriptor()
}

func (TunnelType) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[2]
}

func (x TunnelType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TunnelType.Descriptor instead.
func (TunnelType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

type ExitReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExitReq) Reset() {
	*x = ExitReq{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExitReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitReq) ProtoMessage() {}

func (x *ExitReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitReq.ProtoReflect.Descriptor instead.
func (*ExitReq) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\tnexus.pkg\"\t\n" +
	"\aExitReq*\x84\x03\n" +
	"\vMessageType\x12\x19\n" +
	"\x15ENVELOPE_TYPE_UNKNOWN\x10\x00\x12\r\n" +
	"\tHANDSHAKE\x10\x01\x12\x11\n" +
	"\rHANDSHAKE_ACK\x10\x02\x12\r\n" +
	"\tHEARTBEAT\x10\x03\x12\x11\n" +
	"\rHEARTBEAT_ACK\x10\x04\x12\x0e\n" +
	"\n" +
	"DISCONNECT\x10\x05\x12\b\n" +
	"\x04EXIT\x10\x1e\x12\x0f\n" +
	"\vTUNNEL_OPEN\x10\x1f\x12\x13\n" +
	"\x0fTUNNEL_OPEN_ACK\x10 \x12\b\n" +
	"\x04TASK\x10)\x12\x11\n" +
	"\rTASK_PROGRESS\x10*\x12\x10\n" +
	"\fPROCESS_LIST\x103\x12\x10\n" +
	"\fPROCESS_KILL\x104\x12\r\n" +
	"\tFILE_LIST\x10=\x12\x11\n" +
	"\rFILE_DOWNLOAD\x10>\x12\x0f\n" +
	"\vFILE_UPLOAD\x10?\x12\x0f\n" +
	"\vFILE_DELETE\x10@\x12\x0e\n" +
	"\n" +
	"FILE_MKDIR\x10A\x12\x0f\n" +
	"\vFILE_RENAME\x10B\x12\x10\n" +
	"\fNETWORK_LIST\x10G\x12\r\n" +
	"\tAPP_CHECK\x10Q\x12\x0f\n" +
	"\vAPP_INSTALL\x10R*<\n" +
	"\tErrorCode\x12\x16\n" +
	"\x12ERROR_CODE_UNKNOWN\x10\x00\x12\v\n" +
	"\aSUCCESS\x10\x01\x12\n" +
	"\n" +
	"\x06FAILED\x10\x02*@\n" +
	"\n" +
	"TunnelType\x12\x17\n" +
	"\x13TUNNEL_TYPE_UNKNOWN\x10\x00\x12\a\n" +
	"\x03TCP\x10\x01\x12\a\n" +
	"\x03UDP\x10\x02\x12\a\n" +
	"\x03PTY\x10\x03B)Z'github.com/Tudyha/nexus/pkg/proto/protob\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_proto_goTypes = []any{
	(MessageType)(0), // 0: nexus.pkg.MessageType
	(ErrorCode)(0),   // 1: nexus.pkg.ErrorCode
	(TunnelType)(0),  // 2: nexus.pkg.TunnelType
	(*ExitReq)(nil),  // 3: nexus.pkg.ExitReq
}
var file_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
