syntax = "proto3";

package nexus.pkg;

option go_package = "github.com/Tudyha/nexus/pkg/proto/proto";

// 消息类型
enum MessageType {
  ENVELOPE_TYPE_UNKNOWN = 0;
  // 1-30 系统级消息
  HANDSHAKE     = 1; // 握手请求
  HANDSHAKE_ACK = 2; // 握手响应
  HEARTBEAT     = 3; // 心跳请求
  HEARTBEAT_ACK = 4; // 心跳响应
  DISCONNECT    = 5; // 断开连接

  EXIT = 30; // 客户端退出程序

  // 31-40 tunnel消息
  TUNNEL_OPEN     = 31; // 创建 tunnel
  TUNNEL_OPEN_ACK = 32; // 创建 tunnel 响应

  // 41-50 任务消息
  TASK          = 41; // 下发任务
  TASK_PROGRESS = 42; // 任务进度上报

  // 51-60 进程管理
  PROCESS_LIST = 51; // 列出进程
  PROCESS_KILL = 52; // 终止进程

  // 61-70 文件管理
  FILE_LIST     = 61; // 列出目录
  FILE_DOWNLOAD = 62; // 下载文件
  FILE_UPLOAD   = 63; // 上传文件
  FILE_DELETE   = 64; // 删除文件/目录
  FILE_MKDIR    = 65; // 创建目录
  FILE_RENAME   = 66; // 重命名文件/目录

  // 71-80 网络管理
  NETWORK_LIST = 71; // 列出网络连接

  // 81-90 应用管理
  APP_CHECK   = 81; // 检测已安装应用
  APP_INSTALL = 82; // 安装应用
}

// 错误码
enum ErrorCode {
  ERROR_CODE_UNKNOWN = 0;
  SUCCESS            = 1; // 成功
  FAILED             = 2; // 失败
}

// 隧道类型
enum TunnelType {
  TUNNEL_TYPE_UNKNOWN = 0;
  TCP                 = 1; // TCP 隧道
  UDP                 = 2; // UDP 隧道
  PTY                 = 3; // 伪终端隧道
}

message ExitReq {}