// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.2
// source: file.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileListReq) Reset() {
	*x = FileListReq{}
	mi := &file_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileListReq) ProtoMessage() {}

func (x *FileListReq) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileListReq.ProtoReflect.Descriptor instead.
func (*FileListReq) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{0}
}

func (x *FileListReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	ModTime       int64                  `protobuf:"varint,3,opt,name=mod_time,json=modTime,proto3" json:"mod_time,omitempty"`
	Mode          string                 `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"`
	IsDir         bool                   `protobuf:"varint,5,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Owner         string                 `protobuf:"bytes,6,opt,name=owner,proto3" json:"owner,omitempty"`
	Group         string                 `protobuf:"bytes,7,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{1}
}

func (x *File) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *File) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *File) GetModTime() int64 {
	if x != nil {
		return x.ModTime
	}
	return 0
}

func (x *File) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *File) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *File) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *File) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type FileListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*File                `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileListResp) Reset() {
	*x = FileListResp{}
	mi := &file_file_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileListResp) ProtoMessage() {}

func (x *FileListResp) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileListResp.ProtoReflect.Descriptor instead.
func (*FileListResp) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{2}
}

func (x *FileListResp) GetEntries() []*File {
	if x != nil {
		return x.Entries
	}
	return nil
}

type FileDownloadReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int64                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileDownloadReq) Reset() {
	*x = FileDownloadReq{}
	mi := &file_file_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDownloadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDownloadReq) ProtoMessage() {}

func (x *FileDownloadReq) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDownloadReq.ProtoReflect.Descriptor instead.
func (*FileDownloadReq) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{3}
}

func (x *FileDownloadReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileDownloadReq) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FileDownloadReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type FileDownloadResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	TotalSize     int64                  `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileDownloadResp) Reset() {
	*x = FileDownloadResp{}
	mi := &file_file_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDownloadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDownloadResp) ProtoMessage() {}

func (x *FileDownloadResp) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDownloadResp.ProtoReflect.Descriptor instead.
func (*FileDownloadResp) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{4}
}

func (x *FileDownloadResp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FileDownloadResp) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

type FileUploadReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Append        bool                   `protobuf:"varint,3,opt,name=append,proto3" json:"append,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUploadReq) Reset() {
	*x = FileUploadReq{}
	mi := &file_file_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUploadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadReq) ProtoMessage() {}

func (x *FileUploadReq) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadReq.ProtoReflect.Descriptor instead.
func (*FileUploadReq) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{5}
}

func (x *FileUploadReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileUploadReq) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FileUploadReq) GetAppend() bool {
	if x != nil {
		return x.Append
	}
	return false
}

type FileDeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileDeleteReq) Reset() {
	*x = FileDeleteReq{}
	mi := &file_file_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDeleteReq) ProtoMessage() {}

func (x *FileDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDeleteReq.ProtoReflect.Descriptor instead.
func (*FileDeleteReq) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{6}
}

func (x *FileDeleteReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type FileMkdirReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMkdirReq) Reset() {
	*x = FileMkdirReq{}
	mi := &file_file_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMkdirReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMkdirReq) ProtoMessage() {}

func (x *FileMkdirReq) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMkdirReq.ProtoReflect.Descriptor instead.
func (*FileMkdirReq) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{7}
}

func (x *FileMkdirReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type FileRenameReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldPath       string                 `protobuf:"bytes,1,opt,name=old_path,json=oldPath,proto3" json:"old_path,omitempty"`
	NewPath       string                 `protobuf:"bytes,2,opt,name=new_path,json=newPath,proto3" json:"new_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRenameReq) Reset() {
	*x = FileRenameReq{}
	mi := &file_file_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRenameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRenameReq) ProtoMessage() {}

func (x *FileRenameReq) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRenameReq.ProtoReflect.Descriptor instead.
func (*FileRenameReq) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{8}
}

func (x *FileRenameReq) GetOldPath() string {
	if x != nil {
		return x.OldPath
	}
	return ""
}

func (x *FileRenameReq) GetNewPath() string {
	if x != nil {
		return x.NewPath
	}
	return ""
}

var File_file_proto protoreflect.FileDescriptor

const file_file_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"file.proto\x12\tnexus.pkg\"!\n" +
	"\vFileListReq\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\xa0\x01\n" +
	"\x04File\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x19\n" +
	"\bmod_time\x18\x03 \x01(\x03R\amodTime\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\tR\x04mode\x12\x15\n" +
	"\x06is_dir\x18\x05 \x01(\bR\x05isDir\x12\x14\n" +
	"\x05owner\x18\x06 \x01(\tR\x05owner\x12\x14\n" +
	"\x05group\x18\a \x01(\tR\x05group\"9\n" +
	"\fFileListResp\x12)\n" +
	"\aentries\x18\x01 \x03(\v2\x0f.nexus.pkg.FileR\aentries\"S\n" +
	"\x0fFileDownloadReq\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\"E\n" +
	"\x10FileDownloadResp\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1d\n" +
	"\n" +
	"total_size\x18\x02 \x01(\x03R\ttotalSize\"O\n" +
	"\rFileUploadReq\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x16\n" +
	"\x06append\x18\x03 \x01(\bR\x06append\"#\n" +
	"\rFileDeleteReq\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\"\n" +
	"\fFileMkdirReq\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"E\n" +
	"\rFileRenameReq\x12\x19\n" +
	"\bold_path\x18\x01 \x01(\tR\aoldPath\x12\x19\n" +
	"\bnew_path\x18\x02 \x01(\tR\anewPathB)Z'github.com/Tudyha/nexus/pkg/proto/protob\x06proto3"

var (
	file_file_proto_rawDescOnce sync.Once
	file_file_proto_rawDescData []byte
)

func file_file_proto_rawDescGZIP() []byte {
	file_file_proto_rawDescOnce.Do(func() {
		file_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_file_proto_rawDesc), len(file_file_proto_rawDesc)))
	})
	return file_file_proto_rawDescData
}

var file_file_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_file_proto_goTypes = []any{
	(*FileListReq)(nil),      // 0: nexus.pkg.FileListReq
	(*File)(nil),             // 1: nexus.pkg.File
	(*FileListResp)(nil),     // 2: nexus.pkg.FileListResp
	(*FileDownloadReq)(nil),  // 3: nexus.pkg.FileDownloadReq
	(*FileDownloadResp)(nil), // 4: nexus.pkg.FileDownloadResp
	(*FileUploadReq)(nil),    // 5: nexus.pkg.FileUploadReq
	(*FileDeleteReq)(nil),    // 6: nexus.pkg.FileDeleteReq
	(*FileMkdirReq)(nil),     // 7: nexus.pkg.FileMkdirReq
	(*FileRenameReq)(nil),    // 8: nexus.pkg.FileRenameReq
}
var file_file_proto_depIdxs = []int32{
	1, // 0: nexus.pkg.FileListResp.entries:type_name -> nexus.pkg.File
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_file_proto_init() }
func file_file_proto_init() {
	if File_file_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_file_proto_rawDesc), len(file_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_file_proto_goTypes,
		DependencyIndexes: file_file_proto_depIdxs,
		MessageInfos:      file_file_proto_msgTypes,
	}.Build()
	File_file_proto = out.File
	file_file_proto_goTypes = nil
	file_file_proto_depIdxs = nil
}
