// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: handshake.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ─── Handshake ────────────────────────────────────────────────────────────────
type HandshakeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         int64                  `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`                  // 应用id
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                       // unix 毫秒
	Nonce         string                 `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`                                // 随机数，防重放攻击
	Signature     string                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`                        // 签名：HMAC-SHA256(nonce + timestamp, app_secret)，防重放攻击
	Version       int32                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`                           // Client 版本，Server 可用于决策兼容性
	VersionName   string                 `protobuf:"bytes,7,opt,name=version_name,json=versionName,proto3" json:"version_name,omitempty"` // Client 版本名称，如 "v1.2.3"
	ClientInfo    *ClientInfo            `protobuf:"bytes,6,opt,name=client_info,json=clientInfo,proto3" json:"client_info,omitempty"`    // 新增：Client 相关信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeReq) Reset() {
	*x = HandshakeReq{}
	mi := &file_handshake_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeReq) ProtoMessage() {}

func (x *HandshakeReq) ProtoReflect() protoreflect.Message {
	mi := &file_handshake_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeReq.ProtoReflect.Descriptor instead.
func (*HandshakeReq) Descriptor() ([]byte, []int) {
	return file_handshake_proto_rawDescGZIP(), []int{0}
}

func (x *HandshakeReq) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *HandshakeReq) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HandshakeReq) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *HandshakeReq) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *HandshakeReq) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *HandshakeReq) GetVersionName() string {
	if x != nil {
		return x.VersionName
	}
	return ""
}

func (x *HandshakeReq) GetClientInfo() *ClientInfo {
	if x != nil {
		return x.ClientInfo
	}
	return nil
}

type HandshakeRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeRes) Reset() {
	*x = HandshakeRes{}
	mi := &file_handshake_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRes) ProtoMessage() {}

func (x *HandshakeRes) ProtoReflect() protoreflect.Message {
	mi := &file_handshake_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRes.ProtoReflect.Descriptor instead.
func (*HandshakeRes) Descriptor() ([]byte, []int) {
	return file_handshake_proto_rawDescGZIP(), []int{1}
}

type ClientInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DeviceId        string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`                       // 设备唯一 ID
	Hostname        string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`                                       // 主机名
	HostId          string                 `protobuf:"bytes,3,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`                             // 主机ID
	Username        string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`                                       // 用户名
	Os              string                 `protobuf:"bytes,5,opt,name=os,proto3" json:"os,omitempty"`                                                   // 操作系统
	Arch            string                 `protobuf:"bytes,6,opt,name=arch,proto3" json:"arch,omitempty"`                                               // 架构
	Gid             string                 `protobuf:"bytes,7,opt,name=gid,proto3" json:"gid,omitempty"`                                                 // 组ID
	Uid             string                 `protobuf:"bytes,8,opt,name=uid,proto3" json:"uid,omitempty"`                                                 // 用户ID
	Platform        string                 `protobuf:"bytes,9,opt,name=platform,proto3" json:"platform,omitempty"`                                       // 平台
	PlatformFamily  string                 `protobuf:"bytes,10,opt,name=platform_family,json=platformFamily,proto3" json:"platform_family,omitempty"`    // 平台家族
	PlatformVersion string                 `protobuf:"bytes,11,opt,name=platform_version,json=platformVersion,proto3" json:"platform_version,omitempty"` // 平台版本
	KernelVersion   string                 `protobuf:"bytes,12,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`       // 内核版本
	KernelArch      string                 `protobuf:"bytes,13,opt,name=kernel_arch,json=kernelArch,proto3" json:"kernel_arch,omitempty"`                // 内核架构
	Uptime          uint64                 `protobuf:"varint,14,opt,name=uptime,proto3" json:"uptime,omitempty"`                                         // 运行时间（秒）
	BootTime        uint64                 `protobuf:"varint,15,opt,name=boot_time,json=bootTime,proto3" json:"boot_time,omitempty"`                     // 启动时间（时间戳）
	CpuCount        uint32                 `protobuf:"varint,16,opt,name=cpu_count,json=cpuCount,proto3" json:"cpu_count,omitempty"`                     // CPU数量
	CpuInfo         string                 `protobuf:"bytes,17,opt,name=cpu_info,json=cpuInfo,proto3" json:"cpu_info,omitempty"`                         // CPU信息
	MemTotal        uint64                 `protobuf:"varint,18,opt,name=mem_total,json=memTotal,proto3" json:"mem_total,omitempty"`                     // 内存总量（字节）
	DiskTotal       uint64                 `protobuf:"varint,19,opt,name=disk_total,json=diskTotal,proto3" json:"disk_total,omitempty"`                  // 磁盘总量（字节）
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ClientInfo) Reset() {
	*x = ClientInfo{}
	mi := &file_handshake_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientInfo) ProtoMessage() {}

func (x *ClientInfo) ProtoReflect() protoreflect.Message {
	mi := &file_handshake_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientInfo.ProtoReflect.Descriptor instead.
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return file_handshake_proto_rawDescGZIP(), []int{2}
}

func (x *ClientInfo) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ClientInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *ClientInfo) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *ClientInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ClientInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *ClientInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *ClientInfo) GetGid() string {
	if x != nil {
		return x.Gid
	}
	return ""
}

func (x *ClientInfo) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ClientInfo) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ClientInfo) GetPlatformFamily() string {
	if x != nil {
		return x.PlatformFamily
	}
	return ""
}

func (x *ClientInfo) GetPlatformVersion() string {
	if x != nil {
		return x.PlatformVersion
	}
	return ""
}

func (x *ClientInfo) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *ClientInfo) GetKernelArch() string {
	if x != nil {
		return x.KernelArch
	}
	return ""
}

func (x *ClientInfo) GetUptime() uint64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

func (x *ClientInfo) GetBootTime() uint64 {
	if x != nil {
		return x.BootTime
	}
	return 0
}

func (x *ClientInfo) GetCpuCount() uint32 {
	if x != nil {
		return x.CpuCount
	}
	return 0
}

func (x *ClientInfo) GetCpuInfo() string {
	if x != nil {
		return x.CpuInfo
	}
	return ""
}

func (x *ClientInfo) GetMemTotal() uint64 {
	if x != nil {
		return x.MemTotal
	}
	return 0
}

func (x *ClientInfo) GetDiskTotal() uint64 {
	if x != nil {
		return x.DiskTotal
	}
	return 0
}

var File_handshake_proto protoreflect.FileDescriptor

const file_handshake_proto_rawDesc = "" +
	"\n" +
	"\x0fhandshake.proto\x12\tnexus.pkg\"\xec\x01\n" +
	"\fHandshakeReq\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\x03R\x05appId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\tR\x05nonce\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\tR\tsignature\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x05R\aversion\x12!\n" +
	"\fversion_name\x18\a \x01(\tR\vversionName\x126\n" +
	"\vclient_info\x18\x06 \x01(\v2\x15.nexus.pkg.ClientInfoR\n" +
	"clientInfo\"\x0e\n" +
	"\fHandshakeRes\"\xa3\x04\n" +
	"\n" +
	"ClientInfo\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x17\n" +
	"\ahost_id\x18\x03 \x01(\tR\x06hostId\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x0e\n" +
	"\x02os\x18\x05 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x06 \x01(\tR\x04arch\x12\x10\n" +
	"\x03gid\x18\a \x01(\tR\x03gid\x12\x10\n" +
	"\x03uid\x18\b \x01(\tR\x03uid\x12\x1a\n" +
	"\bplatform\x18\t \x01(\tR\bplatform\x12'\n" +
	"\x0fplatform_family\x18\n" +
	" \x01(\tR\x0eplatformFamily\x12)\n" +
	"\x10platform_version\x18\v \x01(\tR\x0fplatformVersion\x12%\n" +
	"\x0ekernel_version\x18\f \x01(\tR\rkernelVersion\x12\x1f\n" +
	"\vkernel_arch\x18\r \x01(\tR\n" +
	"kernelArch\x12\x16\n" +
	"\x06uptime\x18\x0e \x01(\x04R\x06uptime\x12\x1b\n" +
	"\tboot_time\x18\x0f \x01(\x04R\bbootTime\x12\x1b\n" +
	"\tcpu_count\x18\x10 \x01(\rR\bcpuCount\x12\x19\n" +
	"\bcpu_info\x18\x11 \x01(\tR\acpuInfo\x12\x1b\n" +
	"\tmem_total\x18\x12 \x01(\x04R\bmemTotal\x12\x1d\n" +
	"\n" +
	"disk_total\x18\x13 \x01(\x04R\tdiskTotalB)Z'github.com/Tudyha/nexus/pkg/proto/protob\x06proto3"

var (
	file_handshake_proto_rawDescOnce sync.Once
	file_handshake_proto_rawDescData []byte
)

func file_handshake_proto_rawDescGZIP() []byte {
	file_handshake_proto_rawDescOnce.Do(func() {
		file_handshake_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_handshake_proto_rawDesc), len(file_handshake_proto_rawDesc)))
	})
	return file_handshake_proto_rawDescData
}

var file_handshake_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_handshake_proto_goTypes = []any{
	(*HandshakeReq)(nil), // 0: nexus.pkg.HandshakeReq
	(*HandshakeRes)(nil), // 1: nexus.pkg.HandshakeRes
	(*ClientInfo)(nil),   // 2: nexus.pkg.ClientInfo
}
var file_handshake_proto_depIdxs = []int32{
	2, // 0: nexus.pkg.HandshakeReq.client_info:type_name -> nexus.pkg.ClientInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_handshake_proto_init() }
func file_handshake_proto_init() {
	if File_handshake_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_handshake_proto_rawDesc), len(file_handshake_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_handshake_proto_goTypes,
		DependencyIndexes: file_handshake_proto_depIdxs,
		MessageInfos:      file_handshake_proto_msgTypes,
	}.Build()
	File_handshake_proto = out.File
	file_handshake_proto_goTypes = nil
	file_handshake_proto_depIdxs = nil
}
