// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.2
// source: heartbeat.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeartbeatReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuStat       *CpuStat               `protobuf:"bytes,1,opt,name=cpu_stat,json=cpuStat,proto3" json:"cpu_stat,omitempty"`    // Client 当前 CPU 负载快照
	MemStat       *MemStat               `protobuf:"bytes,2,opt,name=mem_stat,json=memStat,proto3" json:"mem_stat,omitempty"`    // Client 当前内存负载快照
	DiskStat      *DiskStat              `protobuf:"bytes,3,opt,name=disk_stat,json=diskStat,proto3" json:"disk_stat,omitempty"` // Client 当前磁盘负载快照
	NetStat       *NetStat               `protobuf:"bytes,4,opt,name=net_stat,json=netStat,proto3" json:"net_stat,omitempty"`    // Client 当前网络负载快照
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatReq) Reset() {
	*x = HeartbeatReq{}
	mi := &file_heartbeat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatReq) ProtoMessage() {}

func (x *HeartbeatReq) ProtoReflect() protoreflect.Message {
	mi := &file_heartbeat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatReq.ProtoReflect.Descriptor instead.
func (*HeartbeatReq) Descriptor() ([]byte, []int) {
	return file_heartbeat_proto_rawDescGZIP(), []int{0}
}

func (x *HeartbeatReq) GetCpuStat() *CpuStat {
	if x != nil {
		return x.CpuStat
	}
	return nil
}

func (x *HeartbeatReq) GetMemStat() *MemStat {
	if x != nil {
		return x.MemStat
	}
	return nil
}

func (x *HeartbeatReq) GetDiskStat() *DiskStat {
	if x != nil {
		return x.DiskStat
	}
	return nil
}

func (x *HeartbeatReq) GetNetStat() *NetStat {
	if x != nil {
		return x.NetStat
	}
	return nil
}

type HeartbeatResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResp) Reset() {
	*x = HeartbeatResp{}
	mi := &file_heartbeat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResp) ProtoMessage() {}

func (x *HeartbeatResp) ProtoReflect() protoreflect.Message {
	mi := &file_heartbeat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResp.ProtoReflect.Descriptor instead.
func (*HeartbeatResp) Descriptor() ([]byte, []int) {
	return file_heartbeat_proto_rawDescGZIP(), []int{1}
}

// CPU负载
type CpuStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Percent       float64                `protobuf:"fixed64,1,opt,name=percent,proto3" json:"percent,omitempty"` // CPU使用率
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CpuStat) Reset() {
	*x = CpuStat{}
	mi := &file_heartbeat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CpuStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpuStat) ProtoMessage() {}

func (x *CpuStat) ProtoReflect() protoreflect.Message {
	mi := &file_heartbeat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpuStat.ProtoReflect.Descriptor instead.
func (*CpuStat) Descriptor() ([]byte, []int) {
	return file_heartbeat_proto_rawDescGZIP(), []int{2}
}

func (x *CpuStat) GetPercent() float64 {
	if x != nil {
		return x.Percent
	}
	return 0
}

// 内存负载
type MemStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         uint64                 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Used          uint64                 `protobuf:"varint,2,opt,name=used,proto3" json:"used,omitempty"`
	Free          uint64                 `protobuf:"varint,3,opt,name=free,proto3" json:"free,omitempty"`
	Cached        uint64                 `protobuf:"varint,4,opt,name=cached,proto3" json:"cached,omitempty"`
	Buffers       uint64                 `protobuf:"varint,5,opt,name=buffers,proto3" json:"buffers,omitempty"`
	Available     uint64                 `protobuf:"varint,6,opt,name=available,proto3" json:"available,omitempty"`
	UsedPercent   float64                `protobuf:"fixed64,7,opt,name=used_percent,json=usedPercent,proto3" json:"used_percent,omitempty"`
	SwapTotal     uint64                 `protobuf:"varint,8,opt,name=swap_total,json=swapTotal,proto3" json:"swap_total,omitempty"`
	SwapUsed      uint64                 `protobuf:"varint,9,opt,name=swap_used,json=swapUsed,proto3" json:"swap_used,omitempty"`
	SwapFree      uint64                 `protobuf:"varint,10,opt,name=swap_free,json=swapFree,proto3" json:"swap_free,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemStat) Reset() {
	*x = MemStat{}
	mi := &file_heartbeat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemStat) ProtoMessage() {}

func (x *MemStat) ProtoReflect() protoreflect.Message {
	mi := &file_heartbeat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemStat.ProtoReflect.Descriptor instead.
func (*MemStat) Descriptor() ([]byte, []int) {
	return file_heartbeat_proto_rawDescGZIP(), []int{3}
}

func (x *MemStat) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *MemStat) GetUsed() uint64 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *MemStat) GetFree() uint64 {
	if x != nil {
		return x.Free
	}
	return 0
}

func (x *MemStat) GetCached() uint64 {
	if x != nil {
		return x.Cached
	}
	return 0
}

func (x *MemStat) GetBuffers() uint64 {
	if x != nil {
		return x.Buffers
	}
	return 0
}

func (x *MemStat) GetAvailable() uint64 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *MemStat) GetUsedPercent() float64 {
	if x != nil {
		return x.UsedPercent
	}
	return 0
}

func (x *MemStat) GetSwapTotal() uint64 {
	if x != nil {
		return x.SwapTotal
	}
	return 0
}

func (x *MemStat) GetSwapUsed() uint64 {
	if x != nil {
		return x.SwapUsed
	}
	return 0
}

func (x *MemStat) GetSwapFree() uint64 {
	if x != nil {
		return x.SwapFree
	}
	return 0
}

// 磁盘负载
type DiskStat struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Device      string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	Mountpoint  string                 `protobuf:"bytes,2,opt,name=mountpoint,proto3" json:"mountpoint,omitempty"`
	Fstype      string                 `protobuf:"bytes,3,opt,name=fstype,proto3" json:"fstype,omitempty"`
	Total       uint64                 `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	Used        uint64                 `protobuf:"varint,5,opt,name=used,proto3" json:"used,omitempty"`
	Free        uint64                 `protobuf:"varint,6,opt,name=free,proto3" json:"free,omitempty"`
	UsedPercent float64                `protobuf:"fixed64,7,opt,name=used_percent,json=usedPercent,proto3" json:"used_percent,omitempty"`
	// 新增：IO 统计（可选，部分挂载点无此数据）
	ReadBytes     uint64 `protobuf:"varint,8,opt,name=read_bytes,json=readBytes,proto3" json:"read_bytes,omitempty"`
	WriteBytes    uint64 `protobuf:"varint,9,opt,name=write_bytes,json=writeBytes,proto3" json:"write_bytes,omitempty"`
	ReadCount     uint64 `protobuf:"varint,10,opt,name=read_count,json=readCount,proto3" json:"read_count,omitempty"`
	WriteCount    uint64 `protobuf:"varint,11,opt,name=write_count,json=writeCount,proto3" json:"write_count,omitempty"`
	IoTimeMs      uint64 `protobuf:"varint,12,opt,name=io_time_ms,json=ioTimeMs,proto3" json:"io_time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskStat) Reset() {
	*x = DiskStat{}
	mi := &file_heartbeat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskStat) ProtoMessage() {}

func (x *DiskStat) ProtoReflect() protoreflect.Message {
	mi := &file_heartbeat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskStat.ProtoReflect.Descriptor instead.
func (*DiskStat) Descriptor() ([]byte, []int) {
	return file_heartbeat_proto_rawDescGZIP(), []int{4}
}

func (x *DiskStat) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *DiskStat) GetMountpoint() string {
	if x != nil {
		return x.Mountpoint
	}
	return ""
}

func (x *DiskStat) GetFstype() string {
	if x != nil {
		return x.Fstype
	}
	return ""
}

func (x *DiskStat) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *DiskStat) GetUsed() uint64 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *DiskStat) GetFree() uint64 {
	if x != nil {
		return x.Free
	}
	return 0
}

func (x *DiskStat) GetUsedPercent() float64 {
	if x != nil {
		return x.UsedPercent
	}
	return 0
}

func (x *DiskStat) GetReadBytes() uint64 {
	if x != nil {
		return x.ReadBytes
	}
	return 0
}

func (x *DiskStat) GetWriteBytes() uint64 {
	if x != nil {
		return x.WriteBytes
	}
	return 0
}

func (x *DiskStat) GetReadCount() uint64 {
	if x != nil {
		return x.ReadCount
	}
	return 0
}

func (x *DiskStat) GetWriteCount() uint64 {
	if x != nil {
		return x.WriteCount
	}
	return 0
}

func (x *DiskStat) GetIoTimeMs() uint64 {
	if x != nil {
		return x.IoTimeMs
	}
	return 0
}

// 网络负载
type NetStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BytesSent     float64                `protobuf:"fixed64,1,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	BytesRecv     float64                `protobuf:"fixed64,2,opt,name=bytes_recv,json=bytesRecv,proto3" json:"bytes_recv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetStat) Reset() {
	*x = NetStat{}
	mi := &file_heartbeat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetStat) ProtoMessage() {}

func (x *NetStat) ProtoReflect() protoreflect.Message {
	mi := &file_heartbeat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetStat.ProtoReflect.Descriptor instead.
func (*NetStat) Descriptor() ([]byte, []int) {
	return file_heartbeat_proto_rawDescGZIP(), []int{5}
}

func (x *NetStat) GetBytesSent() float64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *NetStat) GetBytesRecv() float64 {
	if x != nil {
		return x.BytesRecv
	}
	return 0
}

var File_heartbeat_proto protoreflect.FileDescriptor

const file_heartbeat_proto_rawDesc = "" +
	"\n" +
	"\x0fheartbeat.proto\x12\tnexus.pkg\"\xcd\x01\n" +
	"\fHeartbeatReq\x12-\n" +
	"\bcpu_stat\x18\x01 \x01(\v2\x12.nexus.pkg.CpuStatR\acpuStat\x12-\n" +
	"\bmem_stat\x18\x02 \x01(\v2\x12.nexus.pkg.MemStatR\amemStat\x120\n" +
	"\tdisk_stat\x18\x03 \x01(\v2\x13.nexus.pkg.DiskStatR\bdiskStat\x12-\n" +
	"\bnet_stat\x18\x04 \x01(\v2\x12.nexus.pkg.NetStatR\anetStat\"\x0f\n" +
	"\rHeartbeatResp\"#\n" +
	"\aCpuStat\x12\x18\n" +
	"\apercent\x18\x01 \x01(\x01R\apercent\"\x93\x02\n" +
	"\aMemStat\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x04R\x05total\x12\x12\n" +
	"\x04used\x18\x02 \x01(\x04R\x04used\x12\x12\n" +
	"\x04free\x18\x03 \x01(\x04R\x04free\x12\x16\n" +
	"\x06cached\x18\x04 \x01(\x04R\x06cached\x12\x18\n" +
	"\abuffers\x18\x05 \x01(\x04R\abuffers\x12\x1c\n" +
	"\tavailable\x18\x06 \x01(\x04R\tavailable\x12!\n" +
	"\fused_percent\x18\a \x01(\x01R\vusedPercent\x12\x1d\n" +
	"\n" +
	"swap_total\x18\b \x01(\x04R\tswapTotal\x12\x1b\n" +
	"\tswap_used\x18\t \x01(\x04R\bswapUsed\x12\x1b\n" +
	"\tswap_free\x18\n" +
	" \x01(\x04R\bswapFree\"\xd9\x02\n" +
	"\bDiskStat\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x1e\n" +
	"\n" +
	"mountpoint\x18\x02 \x01(\tR\n" +
	"mountpoint\x12\x16\n" +
	"\x06fstype\x18\x03 \x01(\tR\x06fstype\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x04R\x05total\x12\x12\n" +
	"\x04used\x18\x05 \x01(\x04R\x04used\x12\x12\n" +
	"\x04free\x18\x06 \x01(\x04R\x04free\x12!\n" +
	"\fused_percent\x18\a \x01(\x01R\vusedPercent\x12\x1d\n" +
	"\n" +
	"read_bytes\x18\b \x01(\x04R\treadBytes\x12\x1f\n" +
	"\vwrite_bytes\x18\t \x01(\x04R\n" +
	"writeBytes\x12\x1d\n" +
	"\n" +
	"read_count\x18\n" +
	" \x01(\x04R\treadCount\x12\x1f\n" +
	"\vwrite_count\x18\v \x01(\x04R\n" +
	"writeCount\x12\x1c\n" +
	"\n" +
	"io_time_ms\x18\f \x01(\x04R\bioTimeMs\"G\n" +
	"\aNetStat\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x01 \x01(\x01R\tbytesSent\x12\x1d\n" +
	"\n" +
	"bytes_recv\x18\x02 \x01(\x01R\tbytesRecvB)Z'github.com/Tudyha/nexus/pkg/proto/protob\x06proto3"

var (
	file_heartbeat_proto_rawDescOnce sync.Once
	file_heartbeat_proto_rawDescData []byte
)

func file_heartbeat_proto_rawDescGZIP() []byte {
	file_heartbeat_proto_rawDescOnce.Do(func() {
		file_heartbeat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_heartbeat_proto_rawDesc), len(file_heartbeat_proto_rawDesc)))
	})
	return file_heartbeat_proto_rawDescData
}

var file_heartbeat_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_heartbeat_proto_goTypes = []any{
	(*HeartbeatReq)(nil),  // 0: nexus.pkg.HeartbeatReq
	(*HeartbeatResp)(nil), // 1: nexus.pkg.HeartbeatResp
	(*CpuStat)(nil),       // 2: nexus.pkg.CpuStat
	(*MemStat)(nil),       // 3: nexus.pkg.MemStat
	(*DiskStat)(nil),      // 4: nexus.pkg.DiskStat
	(*NetStat)(nil),       // 5: nexus.pkg.NetStat
}
var file_heartbeat_proto_depIdxs = []int32{
	2, // 0: nexus.pkg.HeartbeatReq.cpu_stat:type_name -> nexus.pkg.CpuStat
	3, // 1: nexus.pkg.HeartbeatReq.mem_stat:type_name -> nexus.pkg.MemStat
	4, // 2: nexus.pkg.HeartbeatReq.disk_stat:type_name -> nexus.pkg.DiskStat
	5, // 3: nexus.pkg.HeartbeatReq.net_stat:type_name -> nexus.pkg.NetStat
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_heartbeat_proto_init() }
func file_heartbeat_proto_init() {
	if File_heartbeat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_heartbeat_proto_rawDesc), len(file_heartbeat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_heartbeat_proto_goTypes,
		DependencyIndexes: file_heartbeat_proto_depIdxs,
		MessageInfos:      file_heartbeat_proto_msgTypes,
	}.Build()
	File_heartbeat_proto = out.File
	file_heartbeat_proto_goTypes = nil
	file_heartbeat_proto_depIdxs = nil
}
