// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.2
// source: process.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessListReq) Reset() {
	*x = ProcessListReq{}
	mi := &file_process_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessListReq) ProtoMessage() {}

func (x *ProcessListReq) ProtoReflect() protoreflect.Message {
	mi := &file_process_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessListReq.ProtoReflect.Descriptor instead.
func (*ProcessListReq) Descriptor() ([]byte, []int) {
	return file_process_proto_rawDescGZIP(), []int{0}
}

type Process struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Ppid          int32                  `protobuf:"varint,3,opt,name=ppid,proto3" json:"ppid,omitempty"`
	Threads       int32                  `protobuf:"varint,4,opt,name=threads,proto3" json:"threads,omitempty"`
	User          string                 `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	CpuPercent    float64                `protobuf:"fixed64,6,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemPercent    float64                `protobuf:"fixed64,7,opt,name=mem_percent,json=memPercent,proto3" json:"mem_percent,omitempty"`
	MemRss        int64                  `protobuf:"varint,8,opt,name=mem_rss,json=memRss,proto3" json:"mem_rss,omitempty"`
	Status        string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	StartTime     string                 `protobuf:"bytes,10,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Process) Reset() {
	*x = Process{}
	mi := &file_process_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Process) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Process) ProtoMessage() {}

func (x *Process) ProtoReflect() protoreflect.Message {
	mi := &file_process_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Process.ProtoReflect.Descriptor instead.
func (*Process) Descriptor() ([]byte, []int) {
	return file_process_proto_rawDescGZIP(), []int{1}
}

func (x *Process) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Process) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Process) GetPpid() int32 {
	if x != nil {
		return x.Ppid
	}
	return 0
}

func (x *Process) GetThreads() int32 {
	if x != nil {
		return x.Threads
	}
	return 0
}

func (x *Process) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Process) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *Process) GetMemPercent() float64 {
	if x != nil {
		return x.MemPercent
	}
	return 0
}

func (x *Process) GetMemRss() int64 {
	if x != nil {
		return x.MemRss
	}
	return 0
}

func (x *Process) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Process) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

type ProcessListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Process             `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessListResp) Reset() {
	*x = ProcessListResp{}
	mi := &file_process_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessListResp) ProtoMessage() {}

func (x *ProcessListResp) ProtoReflect() protoreflect.Message {
	mi := &file_process_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessListResp.ProtoReflect.Descriptor instead.
func (*ProcessListResp) Descriptor() ([]byte, []int) {
	return file_process_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessListResp) GetList() []*Process {
	if x != nil {
		return x.List
	}
	return nil
}

type ProcessKillReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Signal        int32                  `protobuf:"varint,2,opt,name=signal,proto3" json:"signal,omitempty"` // 默认 15 (SIGTERM)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessKillReq) Reset() {
	*x = ProcessKillReq{}
	mi := &file_process_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessKillReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessKillReq) ProtoMessage() {}

func (x *ProcessKillReq) ProtoReflect() protoreflect.Message {
	mi := &file_process_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessKillReq.ProtoReflect.Descriptor instead.
func (*ProcessKillReq) Descriptor() ([]byte, []int) {
	return file_process_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessKillReq) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessKillReq) GetSignal() int32 {
	if x != nil {
		return x.Signal
	}
	return 0
}

var File_process_proto protoreflect.FileDescriptor

const file_process_proto_rawDesc = "" +
	"\n" +
	"\rprocess.proto\x12\tnexus.pkg\"\x10\n" +
	"\x0eProcessListReq\"\x83\x02\n" +
	"\aProcess\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04ppid\x18\x03 \x01(\x05R\x04ppid\x12\x18\n" +
	"\athreads\x18\x04 \x01(\x05R\athreads\x12\x12\n" +
	"\x04user\x18\x05 \x01(\tR\x04user\x12\x1f\n" +
	"\vcpu_percent\x18\x06 \x01(\x01R\n" +
	"cpuPercent\x12\x1f\n" +
	"\vmem_percent\x18\a \x01(\x01R\n" +
	"memPercent\x12\x17\n" +
	"\amem_rss\x18\b \x01(\x03R\x06memRss\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"start_time\x18\n" +
	" \x01(\tR\tstartTime\"9\n" +
	"\x0fProcessListResp\x12&\n" +
	"\x04list\x18\x01 \x03(\v2\x12.nexus.pkg.ProcessR\x04list\":\n" +
	"\x0eProcessKillReq\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x16\n" +
	"\x06signal\x18\x02 \x01(\x05R\x06signalB)Z'github.com/Tudyha/nexus/pkg/proto/protob\x06proto3"

var (
	file_process_proto_rawDescOnce sync.Once
	file_process_proto_rawDescData []byte
)

func file_process_proto_rawDescGZIP() []byte {
	file_process_proto_rawDescOnce.Do(func() {
		file_process_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_process_proto_rawDesc), len(file_process_proto_rawDesc)))
	})
	return file_process_proto_rawDescData
}

var file_process_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_process_proto_goTypes = []any{
	(*ProcessListReq)(nil),  // 0: nexus.pkg.ProcessListReq
	(*Process)(nil),         // 1: nexus.pkg.Process
	(*ProcessListResp)(nil), // 2: nexus.pkg.ProcessListResp
	(*ProcessKillReq)(nil),  // 3: nexus.pkg.ProcessKillReq
}
var file_process_proto_depIdxs = []int32{
	1, // 0: nexus.pkg.ProcessListResp.list:type_name -> nexus.pkg.Process
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_process_proto_init() }
func file_process_proto_init() {
	if File_process_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_process_proto_rawDesc), len(file_process_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_process_proto_goTypes,
		DependencyIndexes: file_process_proto_depIdxs,
		MessageInfos:      file_process_proto_msgTypes,
	}.Build()
	File_process_proto = out.File
	file_process_proto_goTypes = nil
	file_process_proto_depIdxs = nil
}
